apiVersion: v1
kind: Pod
metadata:
  name: selective-volume-pod2
spec:
  containers:
  - name: my-container
    image: busybox
    args: [ "tail", "-f", "/dev/null" ]
    envFrom:
    - secretRef:
        name: my-password
