apiVersion: v1
kind: Service
metadata:
  name: hostname-nodeport-service
spec:
  type: NodePort
  clusterIP: 10.100.100.200
  selector:
    app: web
  ports:
  - name: web-port
    protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30200
