apiVersion: v1
kind: Service
metadata:
  name: hostname-clusterip-service
spec:
  type: ClusterIP
  clusterIP: 10.100.100.100
  selector:
    app: web
  ports:
  - name: web-port
    protocol: TCP
    port: 8080
    targetPort: 80
