apiVersion: batch/v1
kind: Job
metadata:
  name: centos-job
spec:
  completions: 5
  parallelism: 2
  activeDeadlineSeconds: 5
  template:
    spec:
      containers:
      - name: centos-container
        image: centos:8
        command: ["bash"]
        args:
        - "-c"
        - "echo 'Hello World'; sleep 1; echo 'Bye'"
      restartPolicy: Never
