apiVersion: v1
kind: Service
metadata:
  name: my-nodeport-service
spec:
  type: NodePort
  clusterIP: 10.99.99.99
  selector:
    app: web
  ports:
  - name: web-port
    protocol: TCP
    port: 8011
    targetPort: 80
    nodePort: 30111
