apiVersion: v1
kind: Service
metadata:
  name: tomcat-nodeport-service
  labels:
    name: service-tomcat
spec:
  type: NodePort
  selector:
    app: tomcat8
  ports:
  - name: "tomcat8-nework-setting"
    protocol: TCP
    port: 8088
    targetPort: 8080
    nodePort: 30001
