apiVersion: v1
kind: Pod
metadata:
  name: k8s-apache-pod
  labels: 
    app: hi-apache
spec:
  containers:
  - name: apache-container
    image: nginx:latest
    ports:
    - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: hi-apache-svc
spec:
  selector:
    app: hi-apache
  ports:
    - port: 80
      targetPort: 80
  type: LoadBalancer
